预测年收入是否大于50K美元

读取adult.txt文件，最后一列是年收入，并使用KNN算法训练模型，然后使用模型预测一个人的年收入是否大于50

In [1]:
import pandas as pd 

In [8]:
import numpy as np
from sklearn.neighbors import KNeighborsClassifier

In [2]:
salary = pd.read_csv('./adults/adults.txt')
display(salary.shape, salary.head())

(32561, 15)

age         workclass  final_weight  education  education_num  \
0   39         State-gov         77516  Bachelors             13   
1   50  Self-emp-not-inc         83311  Bachelors             13   
2   38           Private        215646    HS-grad              9   
3   53           Private        234721       11th              7   
4   28           Private        338409  Bachelors             13   

       marital_status         occupation   relationship   race     sex  \
0       Never-married       Adm-clerical  Not-in-family  White    Male   
1  Married-civ-spouse    Exec-managerial        Husband  White    Male   
2            Divorced  Handlers-cleaners  Not-in-family  White    Male   
3  Married-civ-spouse  Handlers-cleaners        Husband  Black    Male   
4  Married-civ-spouse     Prof-specialty           Wife  Black  Female   

   capital_gain  capital_loss  hours_per_week native_country salary  
0          2174             0              40  United-States  <=50K  
1             0             0              13  United-States  <=50K  
2             0             0              40  United-States  <=50K  
3             0             0              40  United-States  <=50K  
4             0             0              40           Cuba  <=50K

In [4]:
salary.columns

Index(['age', 'workclass', 'final_weight', 'education', 'education_num',
       'marital_status', 'occupation', 'relationship', 'race', 'sex',
       'capital_gain', 'capital_loss', 'hours_per_week', 'native_country',
       'salary'],
      dtype='object')

In [5]:
salary.drop(labels=['final_weight', 'education','capital_gain', 'capital_loss'],axis = 1,inplace=True)
salary.head()

age         workclass  education_num      marital_status  \
0   39         State-gov             13       Never-married   
1   50  Self-emp-not-inc             13  Married-civ-spouse   
2   38           Private              9            Divorced   
3   53           Private              7  Married-civ-spouse   
4   28           Private             13  Married-civ-spouse   

          occupation   relationship   race     sex  hours_per_week  \
0       Adm-clerical  Not-in-family  White    Male              40   
1    Exec-managerial        Husband  White    Male              13   
2  Handlers-cleaners  Not-in-family  White    Male              40   
3  Handlers-cleaners        Husband  Black    Male              40   
4     Prof-specialty           Wife  Black  Female              40   

  native_country salary  
0  United-States  <=50K  
1  United-States  <=50K  
2  United-States  <=50K  
3  United-States  <=50K  
4           Cuba  <=50K

In [11]:
X = salary.iloc[:, : -1]

y = salary.salary

In [12]:
knn = KNeighborsClassifier()

knn.fit(X, y)
# str类型不能参与计算,报错

ValueError: could not convert string to float: 'United-States'

In [15]:
X.head()

age         workclass  education_num      marital_status  \
0   39         State-gov             13       Never-married   
1   50  Self-emp-not-inc             13  Married-civ-spouse   
2   38           Private              9            Divorced   
3   53           Private              7  Married-civ-spouse   
4   28           Private             13  Married-civ-spouse   

          occupation   relationship   race     sex  hours_per_week  \
0       Adm-clerical  Not-in-family  White    Male              40   
1    Exec-managerial        Husband  White    Male              13   
2  Handlers-cleaners  Not-in-family  White    Male              40   
3  Handlers-cleaners        Husband  Black    Male              40   
4     Prof-specialty           Wife  Black  Female              40   

  native_country  
0  United-States  
1  United-States  
2  United-States  
3  United-States  
4           Cuba

In [16]:
# workclass字段
w = X['workclass'].unique()
w

array(['State-gov', 'Self-emp-not-inc', 'Private', 'Federal-gov',
       'Local-gov', '?', 'Self-emp-inc', 'Without-pay', 'Never-worked'],
      dtype=object)

In [17]:
# 查找到Private的index
np.argwhere(w == 'Private')

array([[2]], dtype=int64)

In [18]:
def convert(x):
#     workclass列属性改为数字
    return np.argwhere(w == x)[0, 0]

X['workclass'] = X['workclass'].map(convert)

In [20]:
pd.unique(X['workclass'])

array([0, 1, 2, 3, 4, 5, 6, 7, 8], dtype=int64)

In [21]:
X.head()

age  workclass  education_num      marital_status         occupation  \
0   39          0             13       Never-married       Adm-clerical   
1   50          1             13  Married-civ-spouse    Exec-managerial   
2   38          2              9            Divorced  Handlers-cleaners   
3   53          2              7  Married-civ-spouse  Handlers-cleaners   
4   28          2             13  Married-civ-spouse     Prof-specialty   

    relationship   race     sex  hours_per_week native_country  
0  Not-in-family  White    Male              40  United-States  
1        Husband  White    Male              13  United-States  
2  Not-in-family  White    Male              40  United-States  
3        Husband  Black    Male              40  United-States  
4           Wife  Black  Female              40           Cuba

In [23]:
w1 = X['occupation'].unique()
w1

array(['Adm-clerical', 'Exec-managerial', 'Handlers-cleaners',
       'Prof-specialty', 'Other-service', 'Sales', 'Craft-repair',
       'Transport-moving', 'Farming-fishing', 'Machine-op-inspct',
       'Tech-support', '?', 'Protective-serv', 'Armed-Forces',
       'Priv-house-serv'], dtype=object)

In [27]:
np.argwhere(w1 == 'Adm-clerical')

array([[0]], dtype=int64)

In [28]:
def convert_o(x):
    return np.argwhere(w1 == x)[0, 0]

X['occupation'] = X['occupation'].map(convert_o)

In [29]:
X['occupation'].unique()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14],
      dtype=int64)

In [30]:
X.head()

age  workclass  education_num      marital_status  occupation  \
0   39          0             13       Never-married           0   
1   50          1             13  Married-civ-spouse           1   
2   38          2              9            Divorced           2   
3   53          2              7  Married-civ-spouse           2   
4   28          2             13  Married-civ-spouse           3   

    relationship   race     sex  hours_per_week native_country  
0  Not-in-family  White    Male              40  United-States  
1        Husband  White    Male              13  United-States  
2  Not-in-family  White    Male              40  United-States  
3        Husband  Black    Male              40  United-States  
4           Wife  Black  Female              40           Cuba

In [33]:
X.drop(['marital_status', 'relationship', 'race', 'sex', 'native_country'],
       axis=1, inplace=True)
X.head()

age  workclass  education_num  occupation  hours_per_week
0   39          0             13           0              40
1   50          1             13           1              13
2   38          2              9           2              40
3   53          2              7           2              40
4   28          2             13           3              40

In [35]:
X.shape

(32561, 5)

In [38]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=500)

In [44]:
knn = KNeighborsClassifier(n_neighbors=7)

knn.fit(X_train, y_train)

y_ = knn.predict(X_test)

(y_ == y_test).mean()

0.812

In [45]:
knn.score(X_test, y_test)

0.812