In [1]:
import sklearn.datasets as datasets

from sklearn.tree import DecisionTreeClassifier

In [2]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.linear_model import LogisticRegression

In [3]:
iris = datasets.load_iris()

In [4]:
X = iris['data']
y = iris['target']

from sklearn.model_selection import train_test_split

In [220]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

In [9]:
tree = DecisionTreeClassifier()

tree.fit(X_train, y_train)

tree.score(X_test, y_test)

0.8666666666666667

In [10]:
tree.feature_importances_

array([0.04104297, 0.        , 0.00771476, 0.95124226])

In [12]:
# 决策树算法推导出来第二个属性对于分类不重要，所以删除不重要的数据
X_train2 = X_train[: , [0, 2, 3]]

X_test2 = X_test[: , [0, 2, 3]]

In [47]:
tree.fit(X_train2, y_train)

tree.score(X_test2, y_test)

0.9

In [120]:
knn = KNeighborsClassifier(n_neighbors=7)

knn.fit(X_train, y_train)
knn.score(X_test, y_test)

0.9666666666666667

In [137]:
logistic = LogisticRegression()

logistic.fit(X_train, y_train)

logistic.score(X_test, y_test)

H:\env\anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
H:\env\anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:460: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)


0.9666666666666667

In [140]:
# 对于DecisionTree不重要的属性，不一定适用其他算法
logistic.fit(X_train2, y_train)

logistic.score(X_test2, y_test)

H:\env\anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
H:\env\anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:460: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)


0.9333333333333333

In [143]:
knn.predict_proba(X_test)

array([[1.        , 0.        , 0.        ],
       [1.        , 0.        , 0.        ],
       [0.        , 1.        , 0.        ],
       [0.        , 1.        , 0.        ],
       [0.        , 0.42857143, 0.57142857],
       [0.        , 1.        , 0.        ],
       [0.        , 1.        , 0.        ],
       [0.        , 0.14285714, 0.85714286],
       [0.        , 1.        , 0.        ],
       [1.        , 0.        , 0.        ],
       [1.        , 0.        , 0.        ],
       [0.        , 1.        , 0.        ],
       [0.        , 0.71428571, 0.28571429],
       [0.        , 1.        , 0.        ],
       [0.        , 0.        , 1.        ],
       [0.        , 0.85714286, 0.14285714],
       [0.        , 0.42857143, 0.57142857],
       [1.        , 0.        , 0.        ],
       [0.        , 0.        , 1.        ],
       [1.        , 0.        , 0.        ],
       [0.        , 0.        , 1.        ],
       [0.        , 0.28571429, 0.71428571],
       [1.

In [144]:
tree.predict_proba(X_test2)

array([[1., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.]])

In [145]:
# 以e为底求概率的对数
tree.predict_log_proba(X_test2)

H:\env\anaconda3\lib\site-packages\sklearn\tree\tree.py:875: RuntimeWarning: divide by zero encountered in log
  return np.log(proba)


array([[  0., -inf, -inf],
       [  0., -inf, -inf],
       [-inf,   0., -inf],
       [-inf,   0., -inf],
       [-inf,   0., -inf],
       [-inf,   0., -inf],
       [-inf,   0., -inf],
       [-inf, -inf,   0.],
       [-inf,   0., -inf],
       [  0., -inf, -inf],
       [  0., -inf, -inf],
       [-inf,   0., -inf],
       [-inf,   0., -inf],
       [-inf,   0., -inf],
       [-inf, -inf,   0.],
       [-inf,   0., -inf],
       [-inf,   0., -inf],
       [  0., -inf, -inf],
       [-inf, -inf,   0.],
       [  0., -inf, -inf],
       [-inf, -inf,   0.],
       [-inf, -inf,   0.],
       [  0., -inf, -inf],
       [-inf,   0., -inf],
       [  0., -inf, -inf],
       [-inf,   0., -inf],
       [-inf,   0., -inf],
       [-inf,   0., -inf],
       [-inf, -inf,   0.],
       [-inf, -inf,   0.]])

In [213]:
# 随机森林（决策树）
from sklearn.ensemble import RandomForestClassifier

forest= RandomForestClassifier(n_estimators=10)
forest.fit(X_train, y_train)

forest.score(X_test, y_test)

0.8666666666666667

In [224]:
forest= RandomForestClassifier(n_estimators=1)
forest.fit(X_train, y_train)

forest.score(X_test, y_test)

0.9333333333333333

In [216]:
# 梯度提升决策树
from sklearn.ensemble import GradientBoostingClassifier

In [222]:
gbdt = GradientBoostingClassifier()

gbdt.fit(X_train, y_train)

gbdt.score(X_test, y_test)

0.9333333333333333

In [225]:
from sklearn.ensemble import AdaBoostClassifier

In [226]:
ada = AdaBoostClassifier()

ada.fit(X_train, y_train)

ada.score(X_test, y_test)

0.9333333333333333