Logistic Regression虽然名字里带有“回归”，但是它实际上是一种分类方法，用于二分类问题（即输出只有两种）。首先需要找到一个预测函数（h），也称为Sigmoid函数

In [2]:
from sklearn.linear_model import LogisticRegression
import numpy as np
import sklearn.datasets as datasets

In [3]:
# 以鸢尾花举例

iris = datasets.load_iris()

X = iris['data']

y = iris['target']

X.shape

(150, 4)

In [4]:
from sklearn.model_selection import train_test_split

In [6]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)
logistic = LogisticRegression(solver="liblinear")

logistic.fit(X_train, y_train)

y_ = logistic.predict(X_test)

(y_ == y_test).mean()

# LogisticRegression(penalty='l2', dual=False, tol=0.0001, C=1.0, fit_intercept=True, intercept_scaling=1, class_weight=None, random_state=None, solver='warn', max_iter=100, multi_class='warn', verbose=0, warm_start=False, n_jobs=None)
# penalty 惩罚项（正则化）：l1, l2
# tol 误差容忍度
# fit_intercept 是否计算截距
# C 惩罚系数：值越小正则化越强
# solver ："liblinear":小数量级的数据集
#          "lbfgs","sag"or"newton-cg"：大数量级的数据集以及多分类问题
#          "sag"：极大的数据集

H:\env\anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:460: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)


0.9666666666666667

In [11]:
# 回归系数
w_ = logistic.coef_
w_

array([[ 0.38167208,  1.39669072, -2.16632687, -0.97328401],
       [ 0.35054786, -1.40206994,  0.50675574, -1.16670306],
       [-1.56913074, -1.52634475,  2.31573896,  2.37273607]])

In [12]:
# 截距
b_ = logistic.intercept_
b_

array([ 0.25504582,  1.03048209, -1.14168159])

In [14]:
logistic.predict(X_test)

array([1, 2, 1, 0, 2, 0, 2, 1, 2, 0, 0, 1, 2, 0, 2, 0, 2, 2, 0, 0, 1, 0,
       0, 0, 1, 0, 2, 0, 0, 2])

In [13]:
# X_test各预测值概率
# 根据概率大小进行分类
logistic.predict_proba(X_test)

array([[5.75810889e-02, 8.08336579e-01, 1.34082332e-01],
       [7.78785149e-04, 3.19315660e-01, 6.79905554e-01],
       [2.26154852e-02, 6.70775412e-01, 3.06609103e-01],
       [8.06182373e-01, 1.93727289e-01, 9.03378491e-05],
       [3.51182224e-03, 3.26559148e-01, 6.69929030e-01],
       [8.23779593e-01, 1.76199819e-01, 2.05883489e-05],
       [7.51364466e-04, 2.10400026e-01, 7.88848609e-01],
       [5.53806372e-02, 6.89325123e-01, 2.55294240e-01],
       [4.45319540e-04, 1.91048809e-01, 8.08505871e-01],
       [9.47659235e-01, 5.23367500e-02, 4.01466605e-06],
       [8.46321625e-01, 1.53670731e-01, 7.64436250e-06],
       [2.14015191e-02, 8.65777719e-01, 1.12820762e-01],
       [2.10321389e-04, 4.26232288e-01, 5.73557391e-01],
       [8.71152426e-01, 1.28834916e-01, 1.26579593e-05],
       [3.66046150e-04, 2.56663032e-01, 7.42970922e-01],
       [7.68363365e-01, 2.31590994e-01, 4.56411812e-05],
       [4.97740980e-03, 3.62975365e-01, 6.32047225e-01],
       [3.48736272e-04, 3.01776