In [9]:
from sklearn.linear_model import LinearRegression
import numpy as np

In [2]:
import sklearn.datasets as datasets

In [3]:
boston = datasets.load_boston()
boston

{'data': array([[6.3200e-03, 1.8000e+01, 2.3100e+00, ..., 1.5300e+01, 3.9690e+02,
         4.9800e+00],
        [2.7310e-02, 0.0000e+00, 7.0700e+00, ..., 1.7800e+01, 3.9690e+02,
         9.1400e+00],
        [2.7290e-02, 0.0000e+00, 7.0700e+00, ..., 1.7800e+01, 3.9283e+02,
         4.0300e+00],
        ...,
        [6.0760e-02, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9690e+02,
         5.6400e+00],
        [1.0959e-01, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9345e+02,
         6.4800e+00],
        [4.7410e-02, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9690e+02,
         7.8800e+00]]),
 'target': array([24. , 21.6, 34.7, 33.4, 36.2, 28.7, 22.9, 27.1, 16.5, 18.9, 15. ,
        18.9, 21.7, 20.4, 18.2, 19.9, 23.1, 17.5, 20.2, 18.2, 13.6, 19.6,
        15.2, 14.5, 15.6, 13.9, 16.6, 14.8, 18.4, 21. , 12.7, 14.5, 13.2,
        13.1, 13.5, 18.9, 20. , 21. , 24.7, 30.8, 34.9, 26.6, 25.3, 24.7,
        21.2, 19.3, 20. , 16.6, 14.4, 19.4, 19.7, 20.5, 25. , 23.4, 18.9,
        35.4, 24.7, 3

In [5]:
X = boston['data']
y = boston['target']

display(X.shape,y.shape)

(506, 13)

(506,)

In [6]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size = 0.1)

In [7]:
# X -----y之间什么关系 大致上来说线性关系
# 复杂问题简单化
lrg = LinearRegression()

lrg.fit(X_train,y_train)

# 必然是数据计算
y_= lrg.predict(X_test)

In [10]:
# 算法给我们参考，round保留几位小数
display(y_test,np.round(y_,1))

array([15.6, 27.5, 15.3, 14.4, 23.3, 16.1, 30.3, 22. , 13.1, 22.2, 21. ,
       28.7, 21.4, 21.8, 36.4, 29.8,  9.5, 20.4, 30.8, 20.6, 23.5, 24.1,
       22.8, 31.5, 37.6, 28.1, 14.6, 14.1, 22.6, 33.2, 24.8,  7.2, 28.4,
       50. , 17.6, 27.9, 43.5, 36. , 26.5, 11.9,  5. , 23.1, 21.1, 21.2,
       11. , 18.3, 22.4, 23.7, 17.8, 31.7, 22.5])

array([15.7, 32.6, 20.1,  8.7, 28.5, 18.9, 32.8, 27.7, 14.4, 24.1, 20.9,
       25.3, 24. , 21.2, 33. , 32.8, 13.2, 23. , 32. , 16.9, 30.9, 20.4,
       28.8, 31.4, 37.7, 25.2, 19.5, 19. , 27.4, 36.2, 25. , 18. , 28.9,
       36.6, 16.3, 32.6, 39.3, 36.5, 25.9, 22.7,  8.8, 16.9, 20.5, 21.5,
       14.4, 19.2, 23.1, 27.4,  9. , 33.4, 29.3])

In [11]:
# 看一看这个方程

# f(X) = w1*x1 + w2*x2 + ……+b
# 方程必然是由13个系数组成
X.shape

(506, 13)

In [13]:
# 系数
w_ = lrg.coef_
w_

array([-1.01384656e-01,  5.48416414e-02,  3.24535386e-03,  3.05126482e+00,
       -1.94658179e+01,  3.65224488e+00,  2.56604287e-03, -1.62154728e+00,
        3.17114882e-01, -1.23895135e-02, -9.02449228e-01,  8.82373039e-03,
       -5.45263575e-01])

In [14]:
# 截距
b_ = lrg.intercept_
b_

38.41468515651985

In [15]:
X_test

array([[7.50260e-01, 0.00000e+00, 8.14000e+00, 0.00000e+00, 5.38000e-01,
        5.92400e+00, 9.41000e+01, 4.39960e+00, 4.00000e+00, 3.07000e+02,
        2.10000e+01, 3.94330e+02, 1.63000e+01],
       [6.23560e-01, 0.00000e+00, 6.20000e+00, 1.00000e+00, 5.07000e-01,
        6.87900e+00, 7.77000e+01, 3.27210e+00, 8.00000e+00, 3.07000e+02,
        1.74000e+01, 3.90390e+02, 9.93000e+00],
       [1.12658e+00, 0.00000e+00, 1.95800e+01, 1.00000e+00, 8.71000e-01,
        5.01200e+00, 8.80000e+01, 1.61020e+00, 5.00000e+00, 4.03000e+02,
        1.47000e+01, 3.43280e+02, 1.21200e+01],
       [2.53870e-01, 0.00000e+00, 6.91000e+00, 0.00000e+00, 4.48000e-01,
        5.39900e+00, 9.53000e+01, 5.87000e+00, 3.00000e+00, 2.33000e+02,
        1.79000e+01, 3.96900e+02, 3.08100e+01],
       [9.25200e-02, 3.00000e+01, 4.93000e+00, 0.00000e+00, 4.28000e-01,
        6.60600e+00, 4.22000e+01, 6.18990e+00, 6.00000e+00, 3.00000e+02,
        1.66000e+01, 3.83780e+02, 7.37000e+00],
       [2.63548e+00, 0.00000e+

In [17]:
np.round(y_, 1)

array([15.7, 32.6, 20.1,  8.7, 28.5, 18.9, 32.8, 27.7, 14.4, 24.1, 20.9,
       25.3, 24. , 21.2, 33. , 32.8, 13.2, 23. , 32. , 16.9, 30.9, 20.4,
       28.8, 31.4, 37.7, 25.2, 19.5, 19. , 27.4, 36.2, 25. , 18. , 28.9,
       36.6, 16.3, 32.6, 39.3, 36.5, 25.9, 22.7,  8.8, 16.9, 20.5, 21.5,
       14.4, 19.2, 23.1, 27.4,  9. , 33.4, 29.3])

In [16]:
np.round(X_test.dot(w_) + b_, 1)

array([15.7, 32.6, 20.1,  8.7, 28.5, 18.9, 32.8, 27.7, 14.4, 24.1, 20.9,
       25.3, 24. , 21.2, 33. , 32.8, 13.2, 23. , 32. , 16.9, 30.9, 20.4,
       28.8, 31.4, 37.7, 25.2, 19.5, 19. , 27.4, 36.2, 25. , 18. , 28.9,
       36.6, 16.3, 32.6, 39.3, 36.5, 25.9, 22.7,  8.8, 16.9, 20.5, 21.5,
       14.4, 19.2, 23.1, 27.4,  9. , 33.4, 29.3])